# Generated by Django 2.2.7 on 2019-11-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_person_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bio',
        ),
    ]
